// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/common/AppFooter.vue')['default']
    AppPage: typeof import('./../components/page/AppPage.vue')['default']
    AppProvider: typeof import('./../components/common/AppProvider.vue')['default']
    'IconAntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'IconAntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    'IconIc:baselineKeyboardArrowLeft': typeof import('~icons/ic/baseline-keyboard-arrow-left')['default']
    'IconIc:baselineKeyboardArrowRight': typeof import('~icons/ic/baseline-keyboard-arrow-right')['default']
    IconLocalLogo: typeof import('~icons/local/logo')['default']
    'IconMdi:formatIndentDecrease': typeof import('~icons/mdi/format-indent-decrease')['default']
    'IconMdi:formatIndentIncrease': typeof import('~icons/mdi/format-indent-increase')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollX: typeof import('./../components/common/ScrollX.vue')['default']
    SvgIcon: typeof import('./../components/custom/SvgIcon.vue')['default']
  }
}
